global using System.Globalization;
global using System.Text.Json;
global using System.Windows;
global using System.Windows.Media;
global using CycleArc.Models;
global using CycleArc.Providers.ChatGpt;
global using CycleArc.Services;
global using CycleArc.UI;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Color = System.Windows.Media.Color;
global using FontFamily = System.Windows.Media.FontFamily;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using MessageBox = System.Windows.MessageBox;
